Repository mentality-prj/mentality-web, pull requests merged in 2024-11, with the labels that each got.

#6 Add authentication
  .github/workflows/cypress.yml
  app/(auth)/profile/page.tsx
  app/(auth)/signin/page.tsx
  app/api/auth/[...nextauth]/route.ts
  app/page.tsx
  auth.ts
  components/signin-button.tsx
  components/signout-button.tsx
  cypress.config.ts
  cypress/e2e/auth.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
  middleware.ts
  package.json
  yarn.lock
Labels: Run Cypress Tests, Add Reviewers

#8 mock api
  app/(auth)/profile/page.tsx
  auth.ts
  mockApi.js
Labels: Add Reviewers

#11 add eslint security rules
  .eslintrc.json
  .github/reviewers.yml
  package.json
  yarn.lock
Labels: Run Cypress Tests

#13 add auth minor refac
  app/(auth)/profile/page.tsx
  app/api/session/update/route.ts
  auth.ts
  constants/defaults.ts
  helpers/auth.ts
  types/auth.ts
Labels: Run Cypress Tests

#14 fix Routes enum
  app/page.tsx
  constants/routes.ts
Labels: Run Cypress Tests

#15 Fix internationalization
  __tests__/index.test.tsx
  app/[locale]/(auth)/profile/page.tsx
  app/[locale]/(auth)/signin/page.tsx
  app/[locale]/layout.tsx
  app/[locale]/page.tsx
  components/localSwitcher.tsx
  middleware.ts
Labels: Run Cypress Tests, Add Reviewers
